import 'package:cloud_firestore/cloud_firestore.dart';

class Payment {
  final String id;               // Document ID (auto-generated by Firestore)
  final String studentId;        // ID of the student who made the payment
  final String studentName;      // Name of the student
  final String cardNumber;       // Card number used for payment
  final String cardHolderName;   // Name on the card
  final double amountPaid;       // Amount paid by the student
  final DateTime paymentDate;    // Date and time of the payment
  final String status;           // Payment status (e.g., "Paid")

  Payment({
    required this.id,
    required this.studentId,
    required this.studentName,
    required this.cardNumber,
    required this.cardHolderName,
    required this.amountPaid,
    required this.paymentDate,
    required this.status,
  });

  // Factory method to create a Payment instance from Firestore data
  factory Payment.fromFirestore(Map<String, dynamic> data, String documentId) {
    return Payment(
      id: documentId,
      studentId: data['studentId'] ?? '',
      studentName: data['studentName'] ?? '',
      cardNumber: data['cardNumber'] ?? '',
      cardHolderName: data['cardHolderName'] ?? '',
      amountPaid: data['amountPaid']?.toDouble() ?? 0.0,
      paymentDate: (data['paymentDate'] as Timestamp).toDate(),
      status: data['status'] ?? 'Unpaid',
    );
  }

  // Method to convert Payment instance to a map for Firestore
  Map<String, dynamic> toFirestore() {
    return {
      'studentId': studentId,
      'studentName': studentName,
      'cardNumber': cardNumber,
      'cardHolderName': cardHolderName,
      'amountPaid': amountPaid,
      'paymentDate': Timestamp.fromDate(paymentDate),
      'status': status,
    };
  }
}
