// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcKD2vglYpuPzAU_-RhXsx589vGeQTHHo',
    appId: '1:550942466597:web:95b4400c2b95ebbfab55cc',
    messagingSenderId: '550942466597',
    projectId: 'aptechclifton-9c8a0',
    authDomain: 'aptechclifton-9c8a0.firebaseapp.com',
    storageBucket: 'aptechclifton-9c8a0.appspot.com',
    measurementId: 'G-2DLR9X4ZZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvd4NaUc7_KIb4SiKxB-LcjEHD4Dge-h0',
    appId: '1:550942466597:android:f65150646df86e11ab55cc',
    messagingSenderId: '550942466597',
    projectId: 'aptechclifton-9c8a0',
    storageBucket: 'aptechclifton-9c8a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQq4AZYyAwpJH8rNSm1oN-AxpYBUgL49Q',
    appId: '1:550942466597:ios:524222104b190cedab55cc',
    messagingSenderId: '550942466597',
    projectId: 'aptechclifton-9c8a0',
    storageBucket: 'aptechclifton-9c8a0.appspot.com',
    iosBundleId: 'com.example.aptechfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQq4AZYyAwpJH8rNSm1oN-AxpYBUgL49Q',
    appId: '1:550942466597:ios:524222104b190cedab55cc',
    messagingSenderId: '550942466597',
    projectId: 'aptechclifton-9c8a0',
    storageBucket: 'aptechclifton-9c8a0.appspot.com',
    iosBundleId: 'com.example.aptechfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcKD2vglYpuPzAU_-RhXsx589vGeQTHHo',
    appId: '1:550942466597:web:5a11d60fc7ab7684ab55cc',
    messagingSenderId: '550942466597',
    projectId: 'aptechclifton-9c8a0',
    authDomain: 'aptechclifton-9c8a0.firebaseapp.com',
    storageBucket: 'aptechclifton-9c8a0.appspot.com',
    measurementId: 'G-KZHEHKK3RE',
  );
}
